### ISSUE TITLE
tag case result at Supreme Court

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/configurable-tagger#1]
nad tabulkou ze soudu

neutral
if sloupec "způsob vyřízení věci" == "ZASTAVENO" 

positive
if sloupec "způsob vyřízení věci" contains "ZR" | "ZAM" | "ZM"

negative
if sloupec "způsob vyřízení věci" == "ODMÍTNUTO"   nebo contains "OD" & not contains "ZR" | "ZAM" | "ZM"

unknown
else

bylo by fajn ještě před spuštěním ověřit, že jsou spisovky v tabulce unikátní, pokud ne, neunikátním přiřadit výsledek unknown (naprosto nevím, podle čeho je tabulka řazená)

+ by bylo fajn 4 kroky taggování spustit nejprve zvlášť a vykoukat, jestli se k některým rozhodnutím nepřiřadí víc tagů zároveň (nemělo by, ale mohla jsem se někde seknout - kdyžtak napiš)

**Comment by repli2dev** [comment]
> že jsou spisovky v tabulce unikátní,

Víme, že nejsou, chceme kontrolovat konzistenci (že ve všech záznamů mají všechny stejný stav).

**Comment by repli2dev** [comment]
Tagování ní zakladě dat od od soudů (resp. od NS) je hotové. Zkontroloval jsem, že dané podmínky jsou momentálně výlučné (tzn. žádný dokument nespadá do více větví).

Spuštění například `php -d memory_limit=2048M www/index.php app:ns-result-tagger`, vyžaduje docela hodně paměti (a selže bez viditelné chyby, když dojde) a trvá řádově minuty.
